### ISSUE TITLE
Filterformat zu unspezifisch (overblocking)

### ISSUE THREAD

**Issue by op3** [TobsA13/ASB#11]
Das aktuelle Format der Filterliste

```
||example.com$document
```

blockiert nicht nur `example.com`, sondern auch `example.completelydifferentdomain.tld`. Richtig wäre

```
||example.com^$document
```

**Comment by pattyland** [comment]
Just a side note: you could submit the correction as a PR! 😃

**Comment by TobsA13** [comment]
Danke dir für die Info. Sorry hatte das hart vergessen.
