### ISSUE TITLE
rs2.de nicht mehr Teil von Axel Springer, dafür andere Radiosender

### ISSUE THREAD

**Issue by bllngr** [TobsA13/ASB#7]
Seit 2014 ist der Axel-Springer-Verlag nicht mehr Teilhaber an der Regiocast.

https://www.horizont.net/medien/nachrichten/Privatradio-Axel-Springer-steigt-bei-Regiocast-aus-118937

rs2.de kann also wahrscheinlich entfernt werden.

Laut https://www.ard-werbung.de/fileadmin/user_upload/media-perspektiven/pdf/2015/052015_vanRinsum.pdf ist Springer jedoch seitdem an folgenden Sendern beteiligt:

Hit Radio FFH 15,0 %
Radio Hamburg 35,0 %
Antenne Bayern 16,0 %
radio ffn 7,6 %
Pressefunk Nordrhein-Westfalen 12,4 %

**Comment by TobsA13** [comment]
Sorry, das es solang gedauert hat. 

rs2.de ist entfernt.

Die anderen 5 waren bereits in der Liste. 

Danke dir.
